### ISSUE TITLE
No such file or directory: '/workspace/road/cache/resnet50I3D512-Pkinetics-b4s8x1x1-roadt3-h3x3x3/model_000030.pth' while testing on ROAD dataset.

### ISSUE THREAD

**Issue by rafayaamirgull** [gurkirt/3D-RetinaNet#17]
**I am running the following command for testing the pre-trained model on ROAD dataset inside a docker continer.**

python3 main.py /workspace/ /workspace/  /workspace/kinetics-pt/ --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=8 --TRAIN_SUBSETS=train_3 --SEQ_LEN=8 --BATCH_SIZE=4 --LR=0.0041

Your working directories are::
LOAD::>  /workspace/ 
SAVE::>  /workspace/
Your model will be initialized using /workspace/kinetics-pt/resnet50I3D.pth
/usr/local/lib/python3.8/dist-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
[INFO: main.py:  190]: 3.8.10 (default, Sep 11 2024, 16:02:53) 
[GCC 9.4.0]
[INFO: datasets.py:  592]: Number of agent: all :: 11 to use: 10
[INFO: datasets.py:  592]: Number of action: all :: 22 to use: 19
[INFO: datasets.py:  592]: Number of loc: all :: 12 to use: 12
[INFO: datasets.py:  592]: Number of duplex: all :: 152 to use: 39
[INFO: datasets.py:  592]: Number of triplet: all :: 1620 to use: 68
[INFO: datasets.py:  674]: Frames with Boxes are 4033 out of 4734 in 2014-06-25-16-45-34_stereo_centre_02
[INFO: datasets.py:  681]: number of start frames: 789
[INFO: datasets.py:  674]: Frames with Boxes are 5724 out of 6000 in 2014-11-18-13-20-12_stereo_centre_05
[INFO: datasets.py:  681]: number of start frames: 1000
[INFO: datasets.py:  674]: Frames with Boxes are 5133 out of 6001 in 2015-03-03-11-31-36_stereo_centre_01
[INFO: datasets.py:  681]: number of start frames: 1000
[INFO: main.py:  245]: Done Loading Dataset Validation Dataset
[INFO: main.py:  260]: 
Lets do dataparallel

[INFO: main.py:  264]: ANCHOR_TYPE: RETINA
[INFO: main.py:  264]: ANNO_ROOT: 
[INFO: main.py:  264]: ARCH: resnet50
[INFO: main.py:  264]: BATCH_SIZE: 4
[INFO: main.py:  264]: CLASSWISE_NMS: False
[INFO: main.py:  264]: CLS_HEAD_TIME_SIZE: 3
[INFO: main.py:  264]: COMPUTE_PATHS: False
[INFO: main.py:  264]: COMPUTE_TUBES: False
[INFO: main.py:  264]: CONF_THRESH: 0.025
[INFO: main.py:  264]: DATASET: road
[INFO: main.py:  264]: DATA_ROOT: /workspace/
[INFO: main.py:  264]: EVAL_EPOCHS: [30]
[INFO: main.py:  264]: FBN: True
[INFO: main.py:  264]: FREEZE_UPTO: 1
[INFO: main.py:  264]: GAMMA: 0.1
[INFO: main.py:  264]: GEN_CONF_THRESH: 0.025
[INFO: main.py:  264]: GEN_NMS: 0.5
[INFO: main.py:  264]: GEN_TOPK: 100
[INFO: main.py:  264]: HEAD_LAYERS: 3
[INFO: main.py:  264]: IOU_THRESH: 0.5
[INFO: main.py:  264]: JOINT_4M_MARGINALS: False
[INFO: main.py:  264]: LOG_START: 10
[INFO: main.py:  264]: LOG_STEP: 10
[INFO: main.py:  264]: LR: 0.0041
[INFO: main.py:  264]: MAN_SEED: 123
[INFO: main.py:  264]: MAX_EPOCHS: 30
[INFO: main.py:  264]: MAX_SEQ_STEP: 1
[INFO: main.py:  264]: MAX_SIZE: 691
[INFO: main.py:  264]: MEANS: [0.485, 0.456, 0.406]
[INFO: main.py:  264]: MILESTONES: [20, 25]
[INFO: main.py:  264]: MIN_SEQ_STEP: 1
[INFO: main.py:  264]: MIN_SIZE: 512
[INFO: main.py:  264]: MODE: gen_dets
[INFO: main.py:  264]: MODEL_PATH: /workspace/kinetics-pt/resnet50I3D.pth
[INFO: main.py:  264]: MODEL_TYPE: I3D
[INFO: main.py:  264]: MOMENTUM: 0.9
[INFO: main.py:  264]: MULTI_GPUS: True
[INFO: main.py:  264]: NEGTIVE_THRESHOLD: 0.4
[INFO: main.py:  264]: NMS_THRESH: 0.5
[INFO: main.py:  264]: NUM_FEATURE_MAPS: 5
[INFO: main.py:  264]: NUM_WORKERS: 8
[INFO: main.py:  264]: OPTIM: SGD
[INFO: main.py:  264]: PATHS_COST_TYPE: score
[INFO: main.py:  264]: PATHS_IOUTH: 0.5
[INFO: main.py:  264]: PATHS_JUMP_GAP: 4
[INFO: main.py:  264]: PATHS_MINSCORE: 0.1
[INFO: main.py:  264]: PATHS_MIN_LEN: 6
[INFO: main.py:  264]: POSTIVE_THRESHOLD: 0.5
[INFO: main.py:  264]: REG_HEAD_TIME_SIZE: 3
[INFO: main.py:  264]: RESUME: 0
[INFO: main.py:  264]: SAVE_ROOT: /workspace/road/cache/resnet50I3D512-Pkinetics-b4s8x1x1-roadt3-h3x3x3/
[INFO: main.py:  264]: SEQ_LEN: 8
[INFO: main.py:  264]: STDS: [0.229, 0.224, 0.225]
[INFO: main.py:  264]: SUBSETS: ['val_3']
[INFO: main.py:  264]: TENSORBOARD: 1
[INFO: main.py:  264]: TEST_BATCH_SIZE: 1
[INFO: main.py:  264]: TEST_SEQ_LEN: 8
[INFO: main.py:  264]: TEST_SUBSETS: ['val_3']
[INFO: main.py:  264]: TOPK: 10
[INFO: main.py:  264]: TRAIN_SUBSETS: ['train_3']
[INFO: main.py:  264]: TRIM_METHOD: none
[INFO: main.py:  264]: TUBES_ALPHA: 0
[INFO: main.py:  264]: TUBES_EVAL_THRESHS: [0.2, 0.5]
[INFO: main.py:  264]: TUBES_MINLEN: 5
[INFO: main.py:  264]: TUBES_TOPK: 10
[INFO: main.py:  264]: VAL_STEP: 1
[INFO: main.py:  264]: VAL_SUBSETS: ['val_3']
[INFO: main.py:  264]: WEIGHT_DECAY: 0.0001
[INFO: main.py:  264]: all_classes: [['agent_ness'], ['Ped', 'Car', 'Cyc', 'Mobike', 'MedVeh', 'LarVeh', 'Bus', 'EmVeh', 'TL', 'OthTL'], ['Red', 'Amber', 'Green', 'MovAway', 'MovTow', 'Mov', 'Brake', 'Stop', 'IncatLft', 'IncatRht', 'HazLit', 'TurLft', 'TurRht', 'Ovtak', 'Wait2X', 'XingFmLft', 'XingFmRht', 'Xing', 'PushObj'], ['VehLane', 'OutgoLane', 'OutgoCycLane', 'IncomLane', 'IncomCycLane', 'Pav', 'LftPav', 'RhtPav', 'Jun', 'xing', 'BusStop', 'parking'], ['Bus-MovAway', 'Bus-MovTow', 'Bus-Stop', 'Bus-XingFmLft', 'Car-Brake', 'Car-IncatLft', 'Car-IncatRht', 'Car-MovAway', 'Car-MovTow', 'Car-Stop', 'Car-TurLft', 'Car-TurRht', 'Car-XingFmLft', 'Car-XingFmRht', 'Cyc-MovAway', 'Cyc-MovTow', 'Cyc-Stop', 'Cyc-TurLft', 'Cyc-XingFmLft', 'Cyc-XingFmRht', 'LarVeh-Stop', 'MedVeh-IncatLft', 'MedVeh-MovTow', 'MedVeh-Stop', 'MedVeh-TurRht', 'OthTL-Green', 'OthTL-Red', 'Ped-Mov', 'Ped-MovAway', 'Ped-MovTow', 'Ped-PushObj', 'Ped-Stop', 'Ped-Wait2X', 'Ped-Xing', 'Ped-XingFmLft', 'Ped-XingFmRht', 'TL-Amber', 'TL-Green', 'TL-Red'], ['Bus-MovTow-IncomLane', 'Bus-MovTow-Jun', 'Bus-Stop-IncomLane', 'Bus-Stop-VehLane', 'Bus-XingFmLft-Jun', 'Car-Brake-Jun', 'Car-Brake-VehLane', 'Car-IncatLft-Jun', 'Car-IncatLft-VehLane', 'Car-IncatRht-IncomLane', 'Car-IncatRht-Jun', 'Car-MovAway-Jun', 'Car-MovAway-OutgoLane', 'Car-MovAway-VehLane', 'Car-MovTow-IncomLane', 'Car-MovTow-Jun', 'Car-Stop-IncomLane', 'Car-Stop-Jun', 'Car-Stop-VehLane', 'Car-TurLft-Jun', 'Car-TurLft-VehLane', 'Car-TurRht-IncomLane', 'Car-TurRht-Jun', 'Car-XingFmLft-Jun', 'Cyc-MovAway-Jun', 'Cyc-MovAway-LftPav', 'Cyc-MovAway-OutgoCycLane', 'Cyc-MovAway-OutgoLane', 'Cyc-MovAway-VehLane', 'Cyc-MovTow-IncomCycLane', 'Cyc-MovTow-IncomLane', 'Cyc-MovTow-Jun', 'Cyc-MovTow-LftPav', 'Cyc-Stop-IncomCycLane', 'Cyc-Stop-IncomLane', 'Cyc-Stop-Jun', 'Cyc-TurLft-Jun', 'Cyc-XingFmLft-Jun', 'MedVeh-MovTow-IncomLane', 'MedVeh-MovTow-Jun', 'MedVeh-Stop-IncomLane', 'MedVeh-Stop-Jun', 'MedVeh-TurRht-Jun', 'Ped-Mov-Pav', 'Ped-MovAway-LftPav', 'Ped-MovAway-Pav', 'Ped-MovAway-RhtPav', 'Ped-MovTow-IncomLane', 'Ped-MovTow-LftPav', 'Ped-MovTow-RhtPav', 'Ped-MovTow-VehLane', 'Ped-PushObj-LftPav', 'Ped-PushObj-RhtPav', 'Ped-Stop-BusStop', 'Ped-Stop-LftPav', 'Ped-Stop-Pav', 'Ped-Stop-RhtPav', 'Ped-Stop-VehLane', 'Ped-Wait2X-LftPav', 'Ped-Wait2X-RhtPav', 'Ped-XingFmLft-IncomLane', 'Ped-XingFmLft-Jun', 'Ped-XingFmLft-VehLane', 'Ped-XingFmLft-xing', 'Ped-XingFmRht-IncomLane', 'Ped-XingFmRht-Jun', 'Ped-XingFmRht-RhtPav', 'Ped-XingFmRht-VehLane']]
[INFO: main.py:  264]: ar: 9
[INFO: main.py:  264]: ego_classes: ['AV-Stop', 'AV-Mov', 'AV-TurRht', 'AV-TurLft', 'AV-MovRht', 'AV-MovLft', 'AV-Ovtak']
[INFO: main.py:  264]: exp_name: resnet50I3D512-Pkinetics-b4s8x1x1-roadt3-h3x3x3
[INFO: main.py:  264]: head_size: 256
[INFO: main.py:  264]: hostname: rafay-legion-s7
[INFO: main.py:  264]: label_types: ['agent_ness', 'agent', 'action', 'loc', 'duplex', 'triplet']
[INFO: main.py:  264]: log_dir: logs/resnet50I3D512-Pkinetics-b4s8x1x1-roadt3-h3x3x3/
[INFO: main.py:  264]: model_3d_layers: [[0, 1, 2], [0, 2], [0, 2, 4], [0, 1]]
[INFO: main.py:  264]: model_init: kinetics
[INFO: main.py:  264]: model_perms: [3, 4, 6, 3]
[INFO: main.py:  264]: model_subtype: I3D
[INFO: main.py:  264]: non_local_inds: [[], [], [], []]
[INFO: main.py:  264]: num_classes: 149
[INFO: main.py:  264]: num_classes_list: [1, 10, 19, 12, 39, 68]
[INFO: main.py:  264]: num_ego_classes: 7
[INFO: main.py:  264]: num_label_types: 6
[INFO: main.py:  264]: skip_beggning: 2
[INFO: main.py:  264]: skip_ending: 2
[INFO: main.py:  264]: user: root
[INFO: gen_dets.py:   32]: Testing at 30
[INFO: gen_dets.py:   35]: detection saving dir is :: /workspace/road/cache/resnet50I3D512-Pkinetics-b4s8x1x1-roadt3-h3x3x3/detections-30-08-50/
/workspace/gen_dets.py:60: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  net.load_state_dict(torch.load(args.MODEL_PATH))
Traceback (most recent call last):
  File "main.py", line 286, in <module>
    main()
  File "main.py", line 276, in main
    gen_dets(args, net, val_dataset)
  File "/workspace/gen_dets.py", line 60, in gen_dets
    net.load_state_dict(torch.load(args.MODEL_PATH))
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/road/cache/resnet50I3D512-Pkinetics-b4s8x1x1-roadt3-h3x3x3/model_000030.pth'

**Comment by rafayaamirgull** [comment]
@gurkirt  @salmank255 can you please give it a sight? I am looking forward to getting benefit from this amazing code base.
Thanks

**Comment by salmank255** [comment]
Dear @rafayaamirgull, you must train a model to get the weights before testing (gen_dets). There is one pre-trained model (https://drive.google.com/drive/folders/1tOwQtQD3HWiTTp_ZgPCEWd4W-UKiglbt) which you can use but do update the path or create all these folders and put the weights in respective directory.

**Comment by rafayaamirgull** [comment]
Thanks, @salmank255, It works.
