### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Deep-learning999** [gurkirt/3D-RetinaNet#2]
/python3.8/shutil.py", line 244, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: './road/cache/resnet50I3D512-Pkinetics-b4s8x1x1-roadt3-h3x3x3/source/__init__.py' and '/road/cache/resnet50I3D512-Pkinetics-b4s8x1x1-roadt3-h3x3x3//source/__init__.py' are the same file

**Comment by Deep-learning999** [comment]
149]: Itration [1/30]000181/319380 loc-loss 1.01(0.97) cls-loss 1.05(1.07) average-loss 1.03(1.02) DataTime 0.03(0.03) Timer 11.17(11.13)
The last error has been solved, but the training is very slow. It takes 100 hours per sentence for a single GPU.

**Comment by Deep-learning999** [comment]
Error in assessment


[INFO: main.py:  263]: model_init: kinetics
[INFO: main.py:  263]: model_perms: [3, 4, 6, 3]
[INFO: main.py:  263]: model_subtype: I3D
[INFO: main.py:  263]: non_local_inds: [[], [], [], []]
[INFO: main.py:  263]: num_classes: 149
[INFO: main.py:  263]: num_classes_list: [1, 10, 19, 12, 39, 68]
[INFO: main.py:  263]: num_ego_classes: 7
[INFO: main.py:  263]: num_label_types: 6
[INFO: main.py:  263]: skip_beggning: 2
[INFO: main.py:  263]: skip_ending: 2
[INFO: main.py:  263]: user: root
[INFO: gen_dets.py:   30]: Testing at 30
[INFO: gen_dets.py:   33]: detection saving dir is :: /hy-nas/12/kinetics400_tiny/yolov3/road/cache/resnet50I3D512-Pkinetics-b1s8x1x1-roadt3-h3x3x3/detections-30-08-50/
Traceback (most recent call last):
  File "main.py", line 285, in <module>
    main()
  File "main.py", line 275, in main
    gen_dets(args, net, val_dataset)
  File "/hy-nas/12/kinetics400_tiny/yolov3/gen_dets.py", line 58, in gen_dets
    net.load_state_dict(torch.load(args.MODEL_PATH))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RetinaNet:
	Missing key(s) in state_dict: "anchors.cell_anchors.0", "anchors.cell_anchors.1", "anchors.cell_anchors.2", "anchors.cell_anchors.3", "anchors.cell_anchors.4", "backbone.conv1.weight", "backbone.bn1.weight", "backbone.bn1.bias", "backbone.bn1.running_mean", "backbone.bn1.running_var", "backbone.layer1.0.conv1.weight", "backbone.layer1.0.bn1.weight", "backbone.layer1.0.bn1.bias", "backbone.layer1.0.bn1.running_mean", "backbone.layer1.0.bn1.running_var", "backbone.layer1.0.conv2.weight", "backbone.layer1.0.bn2.weight", "backbone.layer1.0.bn2.bias", "backbone.layer1.0.bn2.running_mean", "backbone.layer1.0.bn2.running_var", "backbone.layer1.0.conv3.weight", "backbone.layer1.0.bn3.weight", "backbone.layer1.0.bn3.bias", "

**Comment by Deep-learning999** [comment]
Error in assessment


[INFO: main.py:  263]: model_init: kinetics
[INFO: main.py:  263]: model_perms: [3, 4, 6, 3]
[INFO: main.py:  263]: model_subtype: I3D
[INFO: main.py:  263]: non_local_inds: [[], [], [], []]
[INFO: main.py:  263]: num_classes: 149
[INFO: main.py:  263]: num_classes_list: [1, 10, 19, 12, 39, 68]
[INFO: main.py:  263]: num_ego_classes: 7
[INFO: main.py:  263]: num_label_types: 6
[INFO: main.py:  263]: skip_beggning: 2
[INFO: main.py:  263]: skip_ending: 2
[INFO: main.py:  263]: user: root
[INFO: gen_dets.py:   30]: Testing at 30
[INFO: gen_dets.py:   33]: detection saving dir is :: /road/cache/resnet50I3D512-Pkinetics-b1s8x1x1-roadt3-h3x3x3/detections-30-08-50/
Traceback (most recent call last):
  File "main.py", line 285, in <module>
    main()
  File "main.py", line 275, in main
    gen_dets(args, net, val_dataset)
  File "gen_dets.py", line 58, in gen_dets
    net.load_state_dict(torch.load(args.MODEL_PATH))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RetinaNet:
	Missing key(s) in state_dict: "anchors.cell_anchors.0", "anchors.cell_anchors.1", "anchors.cell_anchors.2", "anchors.cell_anchors.3", "anchors.cell_anchors.4", "backbone.conv1.weight", "backbone.bn1.weight", "backbone.bn1.bias", "backbone.bn1.running_mean", "backbone.bn1.running_var", "backbone.layer1.0.conv1.weight", "backbone.layer1.0.bn1.weight", "backbone.layer1.0.bn1.bias", "backbone.layer1.0.bn1.running_mean", "backbone.layer1.0.bn1.running_var", "backbone.layer1.0.conv2.weight", "backbone.layer1.0.bn2.weight", "backbone.layer1.0.bn2.bias", "backbone.layer1.0.bn2.running_mean", "backbone.layer1.0.bn2.running_var", "backbone.layer1.0.conv3.weight", "backbone.layer1.0.bn3.weight", "backbone.layer1.0.bn3.bias", "

**Comment by Deep-learning999** [comment]
The last error has been solved
I want to do video real-time inference, how should it be achieved

**Comment by ben-z** [comment]
@Deep-learning999 how did you resolve the first error (shutil.SameFileError)?

**Comment by Deep-learning999** [comment]
> @Deep-learning999你是如何解决第一个错误的（shutil.SameFileError）？

I just simply commented

**Comment by gurkirt** [comment]
> The last error has been solved
> I want to do video real-time inference, how should it be achieved

That is tricky, I haven't look at test time computations of 3D RetinaNet, As I3D use temporal comvolution so it not online. However you can use C2D baseline or RCN, in case of RCN, you will need to write single image model and store hidden stated in buffere to be used at next time step.

**Comment by Deep-learning999** [comment]
Thank you for answering. I have another question. Single GPU training is very slow. Can skip frame input be used. For example, every 7 frames is sampled as one frame, which is the magic training speed. If it can, how should it be implemented?

**Comment by gurkirt** [comment]
I used 4 GPUs for training which take about a day and a half to train, as you can fit only a sample on one GPU, maybe using some other less memory-intensive model could the answer.

As for skipping the step, you will need to evaluate all the frames, if you skip frame that could be a problem unless you can use the sliding window kind of approach where frame 1 is elevated in one sequence and frame two in another and so on until your skip step.  But, I am not sure how that would actually perform. Also skipping the frame might not result in lower training time as you might need to train for more epochs. 

Maybe you can play with C2D with a much smaller sequence (2-3 frames). Similar to AMTnet or ACT. That might fit multiple examples on GPU and also might be much quicker to train.

**Comment by Deep-learning999** [comment]
Thanks for the answer
