### ISSUE TITLE
"We got faulty LOCATION loss" and "We got faulty CLASSIFICATION loss"

### ISSUE THREAD

**Issue by ben-z** [gurkirt/3D-RetinaNet#3]
I've been training on 2x Tesla P100 GPUs and have experienced that the location loss and classification loss suddenly became uncontrollably large. Do you know if this is a numerical error?

<details>
  <summary>Logs</summary>

    [INFO: train.py:  151]: resnet50I3D512-Pkinetics-b2s8x1x1-roadt1-h3x3x3
    [INFO: train.py:  149]: Itration [3/10]010697/052430 loc-loss 0.93(0.88) cls-loss 0.66(0.69) average-loss 0.80(0.78) DataTime 0.06(0.06) Timer 17.22(17.25)
    [INFO: train.py:  149]: Itration [3/10]010707/052430 loc-loss 1.17(0.86) cls-loss 0.68(0.70) average-loss 0.93(0.78) DataTime 0.06(0.06) Timer 17.16(17.23)
    [INFO: train.py:  149]: Itration [3/10]010717/052430 loc-loss 0.91(0.83) cls-loss 0.65(0.70) average-loss 0.78(0.76) DataTime 0.06(0.06) Timer 17.28(17.22)
    [INFO: train.py:  149]: Itration [3/10]010727/052430 loc-loss 0.91(0.87) cls-loss 0.68(0.75) average-loss 0.80(0.81) DataTime 0.06(0.06) Timer 17.22(17.23)
    [INFO: train.py:  149]: Itration [3/10]010737/052430 loc-loss 0.46(0.86) cls-loss 0.33(0.77) average-loss 0.40(0.81) DataTime 0.06(0.06) Timer 17.11(17.22)
    [INFO: train.py:  149]: Itration [3/10]010747/052430 loc-loss 0.95(0.79) cls-loss 0.64(0.68) average-loss 0.79(0.73) DataTime 0.06(0.06) Timer 17.27(17.17)
    [INFO: train.py:  149]: Itration [3/10]010757/052430 loc-loss 0.92(0.80) cls-loss 0.61(0.67) average-loss 0.76(0.74) DataTime 0.06(0.06) Timer 17.20(17.19)
    [INFO: train.py:  149]: Itration [3/10]010767/052430 loc-loss 0.45(0.79) cls-loss 0.34(0.66) average-loss 0.39(0.72) DataTime 0.07(0.06) Timer 17.18(17.19)
    [INFO: train.py:  149]: Itration [3/10]010777/052430 loc-loss 0.83(0.80) cls-loss 0.69(0.66) average-loss 0.76(0.73) DataTime 0.06(0.06) Timer 17.23(17.20)
    [INFO: train.py:  149]: Itration [3/10]010787/052430 loc-loss 0.90(0.83) cls-loss 0.72(0.69) average-loss 0.81(0.76) DataTime 0.06(0.06) Timer 17.22(17.21)
    [INFO: train.py:  149]: Itration [3/10]010797/052430 loc-loss 0.95(0.86) cls-loss 23.27(1.88) average-loss 12.11(1.37) DataTime 0.06(0.06) Timer 17.24(17.21)
    [INFO: train.py:  121]:
    
    
     We got faulty LOCATION loss 5671028.0 55407.1953125
    
    
    
    [INFO: train.py:  125]:
    
    
     We got faulty CLASSIFICATION loss 20.0 55407.1953125
    
    
    
    /pytorch/aten/src/ATen/native/cuda/Loss.cu/pytorch/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [637,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.
    /pytorch/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [637,0,0], thread: [1,0,0] Assertion `input_val >= zero && input_val <= one` failed.
    /pytorch/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [637,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
    /pytorch/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [637,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
    ...
    /pytorch/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [787,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
    /pytorch/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [787,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
    /pytorch/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [787,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
    /pytorch/aten/src/ATen/native/cuda/Loss.cu:111: operator(): block: [787,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
    Traceback (most recent call last):
      File "3D-RetinaNet/main.py", line 285, in <module>
        main()
      File "3D-RetinaNet/main.py", line 271, in main
        train(args, net, train_dataset, val_dataset)
      File "/project/6003853/benzhang/road-dataset/3D-RetinaNet/train.py", line 78, in train
        iteration = run_train(args, train_data_loader, net, optimizer, epoch, iteration)
      File "/project/6003853/benzhang/road-dataset/3D-RetinaNet/train.py", line 110, in run_train
        loss_l, loss_c = net(images, gt_boxes, gt_labels, ego_labels, counts, img_indexs)
      File "/local/benzhang.49255117.0/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
        return forward_call(*input, **kwargs)
      File "/local/benzhang.49255117.0/venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
        outputs = self.parallel_apply(replicas, inputs, kwargs)
      File "/local/benzhang.49255117.0/venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
        return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
      File "/local/benzhang.49255117.0/venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
        output.reraise()
      File "/local/benzhang.49255117.0/venv/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
        raise self.exc_type(msg)
    RuntimeError: Caught RuntimeError in replica 0 on device 0.
    Original Traceback (most recent call last):
      File "/local/benzhang.49255117.0/venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
        output = module(*input, **kwargs)
      File "/local/benzhang.49255117.0/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
        return forward_call(*input, **kwargs)
      File "/project/6003853/benzhang/road-dataset/3D-RetinaNet/models/retinanet.py", line 114, in forward
        return self.criterion(flat_conf, flat_loc, gt_boxes, gt_labels, counts, ancohor_boxes, ego_preds, ego_labels)
      File "/local/benzhang.49255117.0/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
        return forward_call(*input, **kwargs)
      File "/project/6003853/benzhang/road-dataset/3D-RetinaNet/modules/detection_loss.py", line 157, in forward
        masked_preds = ego_preds[mask].reshape(-1, numc) # Remove Ignore preds
    RuntimeError: CUDA error: device-side assert triggered
    CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

</details>

I'm rerunning the training now to see if this is reproducible. I have not seen the same behaviour on RTX 3090s and Tesla V100s.

**Comment by gurkirt** [comment]
What is the learning rate and batch size in both cases?

**Comment by ben-z** [comment]
Good point! Here's how I ran the script (with `BATCH_SIZE=2`):

```bash
python3 3D-RetinaNet/main.py \
        $DATA_DIR \
        $OUTPUT_DIR \
        $PT_DIR \
        --MODE=train \
        --ARCH=resnet50 \
        --MODEL_TYPE=I3D \
        --DATASET=road \
        --TRAIN_SUBSETS=train_1 \
        --VAL_SUBSETS=val_1 \
        --SEQ_LEN=8 \
        --TEST_SEQ_LEN=4 \
        --BATCH_SIZE=$BATCH_SIZE \
        --LR=0.00245 \
        --MILESTONES=6,8 \
        --MAX_EPOCHS=10
```

The repeated training on the same hardware is at epoch 4/10 and has not seen the same errors. Perhaps it was just a fluke!

**Comment by ben-z** [comment]
Feel free to close this if you don't have more comments!

**Comment by gurkirt** [comment]
lt is a bit sensitive to learning rate, you will need to reduce the learning by the same factor with which you reduce batch size, maybe even a little bit further lower down the lr.

**Comment by ben-z** [comment]
Thanks!
