### ISSUE TITLE
UserWarning: An output with one or more elements was resized since it had shape [49], which does not match the required output shape [19]

### ISSUE THREAD

**Issue by ben-z** [gurkirt/3D-RetinaNet#4]
I've trained the baseline a few times on different GPUs and have consistently seen this warning at the beginning of epoch 3:

```bash
/project/6003853/benzhang/road-dataset/3D-RetinaNet/modules/box_utils.py:368: UserWarning: An output with one or more elements was resized since it had shape [49], which does not match the required output shape [19].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:23.)
  torch.index_select(x1, 0, idx, out=xx1)
```

The "required output shape" varies slightly with GPU/batch size:

- The require output shape is `18` when I use 4x Tesla V100 with batch size 4
- The require output shape is `19` when I use 2x Tesla P100 with batch size 2
- The require output shape is `19` when I use 2x T4 with batch size 2
- This warning does not appear when I use 2x RTX 3090 with batch size 4

The training configuration is:

```bash
python3 3D-RetinaNet/main.py \
        $DATA_DIR \
        $OUTPUT_DIR \
        $PT_DIR \
        --MODE=train \
        --ARCH=resnet50 \
        --MODEL_TYPE=I3D \
        --DATASET=road \
        --TRAIN_SUBSETS=train_1 \
        --VAL_SUBSETS=val_1 \
        --SEQ_LEN=8 \
        --TEST_SEQ_LEN=4 \
        --BATCH_SIZE=$BATCH_SIZE \
        --LR=0.00245 \
        --MILESTONES=6,8 \
        --MAX_EPOCHS=10
```

Do you know what might have caused this and is this a noteworthy warning?

**Comment by gurkirt** [comment]
I have not an idea, it would have this impact. Have you checked if the passed idx dimension also changes, maybe that is why the output dimension changes.
