### ISSUE TITLE
GPU utilization problem

### ISSUE THREAD

**Issue by EhsanR47** [gurkirt/3D-RetinaNet#6]
We executed this code on the GPU with the following command:
CUDA_VISIBLE_DEVICES = 0,1,2,3 python3 main.py / path / to / data set / ./checkpoint/ kinetics-pt / --MODE = train --ARCH = resnet50 --MODEL_TYPE = I3D --DATASET = road - TRAIN_SUBSETS = train_3 --SEQ_LEN = 8 - TEST_SEQ_LEN = 8 - BATCH_SIZE = 8 --LR = 0.0041
But it does not use all GPU resources and only one GPU is used. As a result, a long time is needed even for completing one iteration. What can we do to be able to use all GPUs resources?
### Nvidia-smi command output before running the code
![image](https://user-images.githubusercontent.com/78280293/126650953-bc81b665-f547-4f68-80d7-8517b7a39ea5.png)
### Nvidia-smi command output after running the code
![image](https://user-images.githubusercontent.com/78280293/126651589-6eede02d-b958-41ec-9fe8-8808f6f8fc94.png)

**Comment by gurkirt** [comment]
Were you able to solve it?

**Comment by EhsanR47** [comment]
> Were you able to solve it?

We are working on it, but we couldn't solve it until now.

**Comment by gurkirt** [comment]
There might be issues with input arguments. Might be accidentally changed. 
See if your program reach 
https://github.com/gurkirt/3D-RetinaNet/blob/master/main.py#L257
and
https://github.com/gurkirt/3D-RetinaNet/blob/master/main.py#L260
Print something to check.

**Comment by EhsanR47** [comment]
> There might be issues with input arguments. Might be accidentally changed.
> See if your program reach
> https://github.com/gurkirt/3D-RetinaNet/blob/master/main.py#L257
> and
> https://github.com/gurkirt/3D-RetinaNet/blob/master/main.py#L260
> Print something to check.

I checked these. My program reached them. I think the problem is with the hardware config.

**Comment by gurkirt** [comment]
Check if it works on some toy example from pytorch.

**Comment by gurkirt** [comment]
did you solve it finally?
