### ISSUE TITLE
Question about testing

### ISSUE THREAD

**Issue by sapphireh** [gurkirt/3D-RetinaNet#7]
I have seen the 'Testing and Building Tubes' part in Introduction which only used for validation  data, and it didn't provide method for testing set. To build the 'class VideoDataset' for model test, we must need annotation files, likes 'road_trainval_v1.0.json' used in function  '_make_lists_road', however, we don't have the annotation file for testing set. 
So, is there any ways to just test the data

**Comment by gurkirt** [comment]
Thank you for your question. All you need is a list of video names and frame list. 
In line https://github.com/gurkirt/3D-RetinaNet/blob/master/data/datasets.py#L533, return the clip and the rest of the fields can be random numbers but abiding the shapes.

**Comment by gurkirt** [comment]
Does that help?
